version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
  db:
    image: mariadb:latest  # ← MySQL から MariaDB に変更
    environment:
      MARIADB_ROOT_PASSWORD: root  # ← MYSQL_ → MARIADB_ に変更
      MARIADB_DATABASE: mydb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: