version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
  mysql:
    build: ./mysql/db    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: original_mysql_world # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=ryosuke0802   #コンテナ内のMySQLを起動する際のパスワードを設定
